### ISSUE TITLE
Корректировка синтаксиса;

### ISSUE THREAD

**Issue by GithabaCollaba** [ytimenkov/instead-block#12]
Дополнить точку с запятой в код, чтобы синтаксис выглядел корректно

**Comment by ytimenkov** [comment]
Нужен пример кода, который генерируется некорректно. Потому что то, что генерируется из примера - корректный код, запускаемый инстедом.
В Lua разделитель не обязателен. А для разделения элементов списка (`obj`, `way` и т.д. я выбрал запятую, как в других языках).
